### ISSUE TITLE
SecurityError: DOM Exception 18 - Safari 7.1

### ISSUE THREAD

**Issue by peterhough** [nruth/show_me_the_cookies#28]
When using Safari 7.1 I get the error `SecurityError: DOM Exception 18 (Selenium::WebDriver::Error::NoScriptResultError)`

```
SecurityError: DOM Exception 18 (Selenium::WebDriver::Error::NoScriptResultError)
 /Users/peterhough/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/safari/bridge.rb:73:in `raw_execute'
 /Users/peterhough/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/remote/bridge.rb:616:in `execute'
 /Users/peterhough/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/remote/bridge.rb:361:in `getAllCookies'
 /Users/peterhough/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.43.0/lib/selenium/webdriver/common/options.rb:77:in `all_cookies'
 /Users/peterhough/.rvm/gems/ruby-2.1.3/gems/show_me_the_cookies-2.5.0/lib/show_me_the_cookies/adapters/selenium.rb:11:in `get_me_the_cookies'
 /Users/peterhough/.rvm/gems/ruby-2.1.3/gems/show_me_the_cookies-2.5.0/lib/show_me_the_cookies.rb:44:in `get_me_the_cookies'
 /Users/peterhough/workspace/mywebsite/cucumber/features/support/step_helpers.rb:531:in `get_cookies'
 /Users/peterhough/workspace/mywebsite/cucumber/features/support/step_helpers.rb:521:in `set_cookie_policy'
 /Users/peterhough/workspace/mywebsite/cucumber/features/support/config.rb:322:in `Before'
```

The same code works fine in Chrome & Firefox.

Thanks in advance for any help.

**Comment by nruth** [comment]
Closing as stale. I've started a branch that tests how the new Apple safari / webkit webdriver works but it looks like there are still some similar issues with setting cookies. May end up requiring optional write cookies api #35.
